# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/walmis/@DancerProjects/nxflat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/walmis/@DancerProjects/nxflat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/walmis/@DancerProjects/nxflat/CMakeFiles /home/walmis/@DancerProjects/nxflat/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/walmis/@DancerProjects/nxflat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ldnxflat

# Build rule for target.
ldnxflat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ldnxflat
.PHONY : ldnxflat

# fast build rule for target.
ldnxflat/fast:
	$(MAKE) -f CMakeFiles/ldnxflat.dir/build.make CMakeFiles/ldnxflat.dir/build
.PHONY : ldnxflat/fast

#=============================================================================
# Target rules for targets named readnxflat

# Build rule for target.
readnxflat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 readnxflat
.PHONY : readnxflat

# fast build rule for target.
readnxflat/fast:
	$(MAKE) -f CMakeFiles/readnxflat.dir/build.make CMakeFiles/readnxflat.dir/build
.PHONY : readnxflat/fast

#=============================================================================
# Target rules for targets named mknxflat

# Build rule for target.
mknxflat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mknxflat
.PHONY : mknxflat

# fast build rule for target.
mknxflat/fast:
	$(MAKE) -f CMakeFiles/mknxflat.dir/build.make CMakeFiles/mknxflat.dir/build
.PHONY : mknxflat/fast

#=============================================================================
# Target rules for targets named signnxflat

# Build rule for target.
signnxflat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 signnxflat
.PHONY : signnxflat

# fast build rule for target.
signnxflat/fast:
	$(MAKE) -f CMakeFiles/signnxflat.dir/build.make CMakeFiles/signnxflat.dir/build
.PHONY : signnxflat/fast

ldnxflat.o: ldnxflat.c.o

.PHONY : ldnxflat.o

# target to build an object file
ldnxflat.c.o:
	$(MAKE) -f CMakeFiles/ldnxflat.dir/build.make CMakeFiles/ldnxflat.dir/ldnxflat.c.o
.PHONY : ldnxflat.c.o

ldnxflat.i: ldnxflat.c.i

.PHONY : ldnxflat.i

# target to preprocess a source file
ldnxflat.c.i:
	$(MAKE) -f CMakeFiles/ldnxflat.dir/build.make CMakeFiles/ldnxflat.dir/ldnxflat.c.i
.PHONY : ldnxflat.c.i

ldnxflat.s: ldnxflat.c.s

.PHONY : ldnxflat.s

# target to generate assembly for a file
ldnxflat.c.s:
	$(MAKE) -f CMakeFiles/ldnxflat.dir/build.make CMakeFiles/ldnxflat.dir/ldnxflat.c.s
.PHONY : ldnxflat.c.s

mknxflat.o: mknxflat.c.o

.PHONY : mknxflat.o

# target to build an object file
mknxflat.c.o:
	$(MAKE) -f CMakeFiles/mknxflat.dir/build.make CMakeFiles/mknxflat.dir/mknxflat.c.o
.PHONY : mknxflat.c.o

mknxflat.i: mknxflat.c.i

.PHONY : mknxflat.i

# target to preprocess a source file
mknxflat.c.i:
	$(MAKE) -f CMakeFiles/mknxflat.dir/build.make CMakeFiles/mknxflat.dir/mknxflat.c.i
.PHONY : mknxflat.c.i

mknxflat.s: mknxflat.c.s

.PHONY : mknxflat.s

# target to generate assembly for a file
mknxflat.c.s:
	$(MAKE) -f CMakeFiles/mknxflat.dir/build.make CMakeFiles/mknxflat.dir/mknxflat.c.s
.PHONY : mknxflat.c.s

readnxflat.o: readnxflat.c.o

.PHONY : readnxflat.o

# target to build an object file
readnxflat.c.o:
	$(MAKE) -f CMakeFiles/readnxflat.dir/build.make CMakeFiles/readnxflat.dir/readnxflat.c.o
.PHONY : readnxflat.c.o

readnxflat.i: readnxflat.c.i

.PHONY : readnxflat.i

# target to preprocess a source file
readnxflat.c.i:
	$(MAKE) -f CMakeFiles/readnxflat.dir/build.make CMakeFiles/readnxflat.dir/readnxflat.c.i
.PHONY : readnxflat.c.i

readnxflat.s: readnxflat.c.s

.PHONY : readnxflat.s

# target to generate assembly for a file
readnxflat.c.s:
	$(MAKE) -f CMakeFiles/readnxflat.dir/build.make CMakeFiles/readnxflat.dir/readnxflat.c.s
.PHONY : readnxflat.c.s

signnxflat.o: signnxflat.c.o

.PHONY : signnxflat.o

# target to build an object file
signnxflat.c.o:
	$(MAKE) -f CMakeFiles/signnxflat.dir/build.make CMakeFiles/signnxflat.dir/signnxflat.c.o
.PHONY : signnxflat.c.o

signnxflat.i: signnxflat.c.i

.PHONY : signnxflat.i

# target to preprocess a source file
signnxflat.c.i:
	$(MAKE) -f CMakeFiles/signnxflat.dir/build.make CMakeFiles/signnxflat.dir/signnxflat.c.i
.PHONY : signnxflat.c.i

signnxflat.s: signnxflat.c.s

.PHONY : signnxflat.s

# target to generate assembly for a file
signnxflat.c.s:
	$(MAKE) -f CMakeFiles/signnxflat.dir/build.make CMakeFiles/signnxflat.dir/signnxflat.c.s
.PHONY : signnxflat.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ldnxflat"
	@echo "... edit_cache"
	@echo "... readnxflat"
	@echo "... mknxflat"
	@echo "... signnxflat"
	@echo "... ldnxflat.o"
	@echo "... ldnxflat.i"
	@echo "... ldnxflat.s"
	@echo "... mknxflat.o"
	@echo "... mknxflat.i"
	@echo "... mknxflat.s"
	@echo "... readnxflat.o"
	@echo "... readnxflat.i"
	@echo "... readnxflat.s"
	@echo "... signnxflat.o"
	@echo "... signnxflat.i"
	@echo "... signnxflat.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

